class OBJWriter:
    def __init__(self):
        pass
    
    def write_obj(self, filename, vertices, faces):
        """
        Write vertices and faces to OBJ file
        
        Args:
            filename: Output filename
            vertices: Array of vertices (N, 3)
            faces: List of face indices
        """
        with open(filename, 'w') as file:
            file.write("# OBJ file generated by 3D Model Viewer\n")
            
            # Write vertices
            for vertex in vertices:
                file.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
            
            # Write faces (OBJ uses 1-based indexing)
            for face in faces:
                face_line = "f"
                for vertex_index in face:
                    face_line += f" {vertex_index + 1}"
                file.write(face_line + "\n")
    
    def write_simple_obj(self, filename, vertices, faces):
        """Alternative writer with simpler format"""
        with open(filename, 'w') as file:
            # Write vertices
            for v in vertices:
                file.write(f"v {v[0]} {v[1]} {v[2]}\n")
            
            # Write faces
            for f in faces:
                file.write("f")
                for vertex_idx in f:
                    file.write(f" {vertex_idx + 1}")
                file.write("\n")